{% set version = "3007.1" %}

package:
  name: salt
  version: {{ version }}

source:
  fn: salt-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/s/salt/salt-{{ version }}.tar.gz
  sha256: b933ac4cb3e4b1118b46dada55c9cc6bdc6f0f94b4c92877aec44b25c6a28c9a

  patches:
    - setup.py.patch  # [win]

build:
  number: 0
  skip: true  # [win32 or py3k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - jinja2
    - msgpack-python
    - openssl 1.0.*
    - pycrypto
    - pyyaml
    - pyzmq >=2.2.0
    - markupsafe
    - apache-libcloud 0.18*
    - requests
    - tornado
    - pywin32  # [win]

test:
  commands:
    - salt --version  # [not win]
    - salt-minion --version

about:
  home: http://saltstack.com
  license: Apache-2.0
  license_file: LICENSE
  summary: Software to automate the management and configuration of any infrastructure or application at scale

extra:
  recipe-maintainers:
    - basepi
    - nmadhok
