{% set version = "3001.1" %}

package:
  name: salt
  version: {{ version }}

source:
  fn: salt-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/salt/salt-{{ version }}.tar.gz
  sha256: e9ebb4d92fae8dabf21b8749dc126e4a4048bf8f613f5b1b851fe4b8226b5abc

  patches:
    - setup.py.patch  # [win]

build:
  number: 0
  skip: true  # [win32 or py3k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - jinja2
    - msgpack-python
    - openssl 1.0.*
    - pycrypto
    - pyyaml
    - pyzmq >=2.2.0
    - markupsafe
    - apache-libcloud 0.18*
    - requests
    - tornado
    - pywin32  # [win]

test:
  commands:
    - salt --version  # [not win]
    - salt-minion --version

about:
  home: http://saltstack.com
  license: Apache-2.0
  license_file: LICENSE
  summary: Software to automate the management and configuration of any infrastructure or application at scale

extra:
  recipe-maintainers:
    - basepi
    - nmadhok
