{% set version = "2016.3.0" %}

package:
  name: salt
  version: {{ version }}

source:
  fn: salt-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/salt/salt-{{ version }}.tar.gz
  sha256: e316dd103b7faeaa97820197e4d0d7d358519f0ca2a6dcb1d9b718eea801ed30

  patches:
    - setup.py.patch  # [win]

build:
  number: 1001
  skip: True  # [win32 or py3k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - jinja2
    - msgpack-python
    - openssl 1.0.*
    - pycrypto
    - pyyaml
    - pyzmq >=2.2.0
    - markupsafe
    - apache-libcloud 0.18*
    - requests
    - tornado
    - pywin32  # [win]

test:
  commands:
    - salt --version  # [not win]
    - salt-minion --version

about:
  home: http://saltstack.com
  license: Apache 2.0
  summary: Software to automate the management and configuration of any infrastructure or application at scale

extra:
  recipe-maintainers:
    - basepi
    - danielfrg
    - nmadhok
