appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kYCCKXuj3LcJpy/pLPf/Hp2MA0/HBTQ9B/BnQhD9Y0H4UXu8BUQty4btKIHA9QDvB/g/ErWpdq8WuE5DhQjocR2JZ66wt2Lt4s6m6Ox8wAK5plpQ3YGV9IplzVXyGp2GXlvCR/wuYFjerrQAOcO96MOrOH5CBmBQvZLsWVZGGpyb3NBrLbIhCY9Sb//p/0QYtnXefhli7oVmVZnX7b1ZqpUNBjmkE7yi9zH9IVFkhtSV5cJAFst4gjKPS0OdSYDnuyQEGxXVyxh/kbJ1nCz25rP5fUVvxWmTLbRxXJapx9e5yo+9xQLyuZxZPgprOqREZ8kYm800XfFMDPMY1R10hOaQSz1MyxrRYKQhQWP08u8GU3a6KdGI5+PExuH4SxMiUJrqO893U52K4R+JfPDCSeNMase8kW+Se5FIEX15CnG3ISTao/frjsGVVtDEi02ZdjnTd35ogyQbp3ITXU3TiBBRcQDe2pNwtwEoRQrY77d/h/g2deb4CwKGWWpodax91y5UiO/fHx21URKULU+zJPZcJDzbdPzHQx72jZASfH5USAWuc6QFUNqInTLwdWkid0a2QTt0VvcFLgrL6+QEtVdhIWxlwsigUhEtQn3PHT6EhAm4NbB1FfXCCPdTTde9JaIrr2wtCxbXlrTpzkMRI3UToY/BMnnoXXay+UZDszw=}
